/ddsm_controller_node:
  ros__parameters:
    port_name: "/dev/ddsm"
    baud_rate: 115200
    motor_max_rpm: 330
    user_max_rpm: 60
    stop_eps: 0.02
    wheel_radius: 0.08
    wheel_base_x: 0.42
    wheel_base_y: 0.34
    
